[mongodb]
localhost

[redis]
#redis.devresh.online
localhost

[mysql]
#mysql.devresh.online
localhost

[rabbitmq]
#rabbitmq.devresh.online
localhost

[catalogue]
catalogue.devresh.online

[cart]
cart.devresh.online

[user]
user.devresh.online


[shipping]
shipping.devresh.online

[payment]
payment.devresh.online

[frontend]
frontend.devresh.online


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321


[frontend]
172.31.16.218

[local]
localhost

[local:vars]
NAME=Dandu from inventy file
; COURSE=Ansible
; DURATION=20HRS
; TRAINER=DevDandu